In [1]:
import pandas as pd

## Uniforme

In [3]:
#panel5_menor_uni=pd.read_csv("symmetric/5redesmenor/panel_uniform.csv")
panel5_maximo_uni=pd.read_csv("symmetric/5redesmaximo/panel_uniform.csv")
#panel5_median_uni=pd.read_csv("symmetric/5redesmedian/panel_uniform.csv")
panel5_promedio_uni=pd.read_csv("symmetric/5redespromedio/panel_uniform.csv")

## suma producto precio y cantidades despachadas. Despues sumar por batch y promediar expenditure totoal por batch

In [4]:
import ast
import numpy as np
import pandas as pd

def calcular_promedio_por_h(panel, col_cant='cantidades_despachadas', col_precio='precio24', col_h='h'):
    
    def procesar_fila(row):
        # Convertir string a lista
        cantidades = np.array(ast.literal_eval(row[col_cant]), dtype=float)
        precios = np.array(ast.literal_eval(row[col_precio]), dtype=float)
        
        # Multiplicación elemento a elemento
        producto = cantidades * precios
        
        # Suma total de esa fila
        return producto.sum()
    
    # Calcular suma fila por fila
    panel['suma_producto'] = panel.apply(procesar_fila, axis=1)
    
    # Sumar por hora
    suma_por_h = panel.groupby(col_h)['suma_producto'].sum()
    
    # Promedio por hora
    promedio = suma_por_h.mean()
    
    return suma_por_h, promedio

In [6]:
#suma_menor, prom_menor = calcular_promedio_por_h(panel5_menor_uni)
suma_maximo, prom_maximo = calcular_promedio_por_h(panel5_maximo_uni)
#suma_median, prom_median = calcular_promedio_por_h(panel5_median_uni)
suma_promedio, prom_promedio = calcular_promedio_por_h(panel5_promedio_uni)

In [8]:
df_final = pd.DataFrame({
    #'prom_menor': [prom_menor],
    'prom_maximo': [prom_maximo],
    #'prom_median': [prom_median],
    'prom_promedio': [prom_promedio]
})

df_final/1000
# en mil millones

   prom_maximo  prom_promedio
0     6.477323      22.252445

## sumar producto de cantidades y precio, hallar expnditure promedio para cada planta sobre batches.  Despues sumar los promedios

In [11]:
def calcular_promedio_por_id(panel, col_cant='cantidades_despachadas', col_precio='precio24', col_planta='id_planta'):
    
    def procesar_fila(row):
        # Convertir string a lista
        cantidades = np.array(ast.literal_eval(row[col_cant]), dtype=float)
        precios = np.array(ast.literal_eval(row[col_precio]), dtype=float)
        
        # Multiplicación elemento a elemento
        producto = cantidades * precios
        
        # Suma total de esa fila
        return producto.sum()
    
    # Calcular suma fila por fila
    panel['suma_producto'] = panel.apply(procesar_fila, axis=1)
    
    # Sumar por hora
    suma_por_h = panel.groupby(col_planta)['suma_producto'].mean()
    
    # Promedio por hora
    promedio = suma_por_h.sum()
    
    return suma_por_h, promedio

In [13]:
#suma_menor, prom_menor = calcular_promedio_por_id(panel5_menor_uni)
suma_maximo, prom_maximo = calcular_promedio_por_id(panel5_maximo_uni)
#suma_median, prom_median = calcular_promedio_por_id(panel5_median_uni)
suma_promedio, prom_promedio = calcular_promedio_por_id(panel5_promedio_uni)

In [15]:
df_final = pd.DataFrame({
    #'prom_menor': [prom_menor],
    'prom_maximo': [prom_maximo],
    #'prom_median': [prom_median],
    'prom_promedio': [prom_promedio]
})

df_final/1000
# en mil millones

   prom_maximo  prom_promedio
0     6.477323      22.252445

## Discriminatorio

In [16]:
#panel5_menor_pab=pd.read_csv("symmetric/5redesmenor/panel_pay_as_bid.csv")
#panel5_maximo_pab=pd.read_csv("symmetric/5redesmaximo/panel_pay_as_bid.csv")
panel5_median_pab=pd.read_csv("symmetric/5redesmedian/panel_pay_as_bid.csv")
panel5_promedio_pab=pd.read_csv("symmetric/5redespromedio/panel_pay_as_bid.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'symmetric/5redesmedian/panel_pay_as_bid.csv'

In [ ]:
#suma_menor, prom_menor = calcular_promedio_por_h(panel5_menor_pab)
#suma_maximo, prom_maximo = calcular_promedio_por_h(panel5_maximo_pab)
suma_median, prom_median = calcular_promedio_por_h(panel5_median_pab)
suma_promedio, prom_promedio = calcular_promedio_por_h(panel5_promedio_pab)

In [ ]:
prom_median

np.float64(5461.214644777611)

In [ ]:
prom_promedio

np.float64(6288.2778638844475)